version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ecommerce"
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]

  frontend:
    build: ./front/case-join
    container_name: ecommerce-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./front/case-join:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
  node_modules:
